name: CI Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-ci:
    runs-on: ubuntu-latest

    steps:
    # 1. source code dari repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_sqlite
        coverage: none

    # 3. Install dependency Laravel
    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    # 4. file environment untuk CI
    - name: Copy .env
      run: cp .env.example .env

    # 5. Generate APP_KEY
    - name: Generate application key
      run: php artisan key:generate

    # 6. Buat database SQLite (tanpa MySQL)
    - name: Create SQLite database
      run: |
        mkdir -p database
        touch database/database.sqlite

    # 7. Run migration
    - name: Run migrations
      run: php artisan migrate --force

    # 8. Run Laravel tests
    - name: Run tests
      run: php artisan test